//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamGia
    {
        public int masach { get; set; }
        public int matacgia { get; set; }
        public string vaitro { get; set; }
        public string vitri { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual TacGia TacGia { get; set; }
    }
}
